/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.10.v201611111521.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_IVIS_CDL_Client_API_Remote_PROXY_HPP_
#define V1_COM_IVIS_CDL_Client_API_Remote_PROXY_HPP_

#include <v1/com/ivis/CDL/ClientAPIRemoteProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace ivis {
namespace CDL {

template <typename ... _AttributeExtensions>
class ClientAPIRemoteProxy
    : virtual public ClientAPIRemote,
      virtual public ClientAPIRemoteProxyBase,
      virtual public _AttributeExtensions... {
public:
    ClientAPIRemoteProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ClientAPIRemoteProxy();

    typedef ClientAPIRemote InterfaceType;



    /**
     * Returns the wrapper class that provides access to the broadcast notifyData.
     */
    virtual NotifyDataEvent& getNotifyDataEvent() {
        return delegate_->getNotifyDataEvent();
    }

    /**
     * Calls storeData with synchronous semantics.
     *
    * All const parameters are input parameters to this method.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void storeData(const std::string &_domain, const std::string &_subDomain, const std::string &_id, const ClientAPIRemoteTypes::CDLData &_data, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls storeData with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> storeDataAsync(const std::string &_domain, const std::string &_subDomain, const std::string &_id, const ClientAPIRemoteTypes::CDLData &_data, StoreDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr< ClientAPIRemoteProxyBase> delegate_;
};

typedef ClientAPIRemoteProxy<> ClientAPIRemoteProxyDefault;


//
// ClientAPIRemoteProxy Implementation
//
template <typename ... _AttributeExtensions>
ClientAPIRemoteProxy<_AttributeExtensions...>::ClientAPIRemoteProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ClientAPIRemoteProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ClientAPIRemoteProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ClientAPIRemoteProxy<_AttributeExtensions...>::~ClientAPIRemoteProxy() {
}

template <typename ... _AttributeExtensions>
void ClientAPIRemoteProxy<_AttributeExtensions...>::storeData(const std::string &_domain, const std::string &_subDomain, const std::string &_id, const ClientAPIRemoteTypes::CDLData &_data, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
    delegate_->storeData(_domain, _subDomain, _id, _data, _internalCallStatus, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ClientAPIRemoteProxy<_AttributeExtensions...>::storeDataAsync(const std::string &_domain, const std::string &_subDomain, const std::string &_id, const ClientAPIRemoteTypes::CDLData &_data, StoreDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->storeDataAsync(_domain, _subDomain, _id, _data, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ClientAPIRemoteProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ClientAPIRemoteProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ClientAPIRemoteProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ClientAPIRemoteProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ClientAPIRemoteProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace CDL
} // namespace ivis
} // namespace com
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_IVIS_CDL_Client_API_Remote_PROXY_HPP_
