/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.10.v201610310807.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/ivis/CDL/ClientAPIRemoteSomeIPDeployment.hpp>

namespace v1 {
namespace com {
namespace ivis {
namespace CDL {
namespace ClientAPIRemote_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment
CommonAPI::SomeIP::StringDeployment storeData_domainDeployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16LE);
CommonAPI::SomeIP::StringDeployment storeData_subDomainDeployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16LE);
CommonAPI::SomeIP::StringDeployment storeData_idDeployment(0, 4, CommonAPI::SomeIP::StringEncoding::UTF16LE);

// Broadcast-specific deployments

} // namespace ClientAPIRemote_
} // namespace CDL
} // namespace ivis
} // namespace com
} // namespace v1
