/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.v201601121427.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_IVIS_MODEMANAGER_Mode_Manager_STUB_DEFAULT_HPP_
#define V1_COM_IVIS_MODEMANAGER_Mode_Manager_STUB_DEFAULT_HPP_


#include <v1/com/ivis/ModeManager/ModeManagerStub.hpp>
#include <sstream>

namespace v1 {
namespace com {
namespace ivis {
namespace ModeManager {

/**
 * Provides a default implementation for ModeManagerStubRemoteEvent and
 * ModeManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class ModeManagerStubDefault
    : public virtual ModeManagerStub {
public:
    ModeManagerStubDefault();

    ModeManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr<ModeManagerStubAdapter> &_adapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    virtual const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo& getActiveApplicationAttribute();
    virtual const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo& getActiveApplicationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    virtual void setActiveApplicationAttribute(::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo _value);
    virtual void setActiveApplicationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo _value);

    virtual void requestChangeApplication(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationType _app, ::v1::com::ivis::ModeManager::ModeManagerTypes::SubApplicationType _subApp, ::v1::com::ivis::ModeManager::ModeManagerTypes::AppChangeRequester _requester, requestChangeApplicationReply_t _reply);

virtual void fireResponseChangeApplicationEvent(const ::v1::com::ivis::ModeManager::ModeManagerTypes::AppChangeResult &_result, const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo &_currentAppInfo, const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo &_requestAppInfo, const ::v1::com::ivis::ModeManager::ModeManagerTypes::AppChangeRequester &_requester);
virtual void fireActiveApplicationChangedEvent(const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo &_appInfo, const ::v1::com::ivis::ModeManager::ModeManagerTypes::AppChangeRequester &_requester);


protected:
    virtual bool trySetActiveApplicationAttribute(::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo _value);
    virtual bool validateActiveApplicationAttributeRequestedValue(const ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo &_value);
    virtual void onRemoteActiveApplicationAttributeChanged();
    class RemoteEventHandler: public virtual ModeManagerStubRemoteEvent {
    public:
        RemoteEventHandler(ModeManagerStubDefault *_defaultStub);

        virtual bool onRemoteSetActiveApplicationAttribute(::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo _value);
        virtual bool onRemoteSetActiveApplicationAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo _value);
        virtual void onRemoteActiveApplicationAttributeChanged();


    private:
        ModeManagerStubDefault *defaultStub_;
    };
private:
    ModeManagerStubDefault::RemoteEventHandler remoteEventHandler_;

    ::v1::com::ivis::ModeManager::ModeManagerTypes::ApplicationInfo activeApplicationAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace ModeManager
} // namespace ivis
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_IVIS_MODEMANAGER_Mode_Manager_STUB_DEFAULT
