
        /*
        * This file was generated by the CommonAPI Generators.
        * Used org.genivi.commonapi.someip 3.1.5.v201601121433.
        * Used org.franca.core 0.9.1.201412191134.
        *
        * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
        * If a copy of the MPL was not distributed with this file, You can obtain one at
        * http://mozilla.org/MPL/2.0/.
        */
#include <v1/com/ivis/AVInformationProvider/AVInformationTypesSomeIPDeployment.hpp>

namespace v1 {
namespace com {
namespace ivis {
namespace AVInformationProvider {
namespace AVInformationTypes_ {

// typecollection-specific deployments

} // namespace AVInformationTypes_
} // namespace AVInformationProvider
} // namespace ivis
} // namespace com
} // namespace v1
