/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.10.v201611111521.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_Information_STUB_DEFAULT_HPP_
#define V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_Information_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/ivis/AVInformationProvider/AVInformationStub.hpp>
#include <sstream>

#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif

namespace v1 {
namespace com {
namespace ivis {
namespace AVInformationProvider {

/**
 * Provides a default implementation for AVInformationStubRemoteEvent and
 * AVInformationStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT AVInformationStubDefault
    : public virtual AVInformationStub {
public:
    COMMONAPI_EXPORT AVInformationStubDefault();

    COMMONAPI_EXPORT AVInformationStubRemoteEvent* initStubAdapter(const std::shared_ptr< AVInformationStubAdapter> &_adapter);

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source& getCurrentSourceAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source& getCurrentSourceAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setCurrentSourceAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source _value);
    COMMONAPI_EXPORT virtual void setCurrentSourceAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source _value);
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData& getMetaDataAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData& getMetaDataAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setMetaDataAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData _value);
    COMMONAPI_EXPORT virtual void setMetaDataAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData _value);
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition& getPlayPositionAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition& getPlayPositionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setPlayPositionAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition _value);
    COMMONAPI_EXPORT virtual void setPlayPositionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition _value);
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus& getPlayStatusAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus& getPlayStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setPlayStatusAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus _value);
    COMMONAPI_EXPORT virtual void setPlayStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus _value);

    COMMONAPI_EXPORT virtual void requestAction(const std::shared_ptr<CommonAPI::ClientId> _client, AVInformationTypes::Action _action, requestActionReply_t _reply);

    COMMONAPI_EXPORT virtual void fireNotifyAlbumArtEvent(const uint32_t &_totalSegmentCount, const uint32_t &_currentIndex, const std::vector< uint8_t > &_imageData);

    
protected:
    COMMONAPI_EXPORT virtual bool trySetCurrentSourceAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source _value);
    COMMONAPI_EXPORT virtual bool validateCurrentSourceAttributeRequestedValue(const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source &_value);
    COMMONAPI_EXPORT virtual void onRemoteCurrentSourceAttributeChanged();
    COMMONAPI_EXPORT virtual bool trySetMetaDataAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData _value);
    COMMONAPI_EXPORT virtual bool validateMetaDataAttributeRequestedValue(const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData &_value);
    COMMONAPI_EXPORT virtual void onRemoteMetaDataAttributeChanged();
    COMMONAPI_EXPORT virtual bool trySetPlayPositionAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition _value);
    COMMONAPI_EXPORT virtual bool validatePlayPositionAttributeRequestedValue(const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition &_value);
    COMMONAPI_EXPORT virtual void onRemotePlayPositionAttributeChanged();
    COMMONAPI_EXPORT virtual bool trySetPlayStatusAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus _value);
    COMMONAPI_EXPORT virtual bool validatePlayStatusAttributeRequestedValue(const ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus &_value);
    COMMONAPI_EXPORT virtual void onRemotePlayStatusAttributeChanged();
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual AVInformationStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(AVInformationStubDefault *_defaultStub);

        COMMONAPI_EXPORT virtual bool onRemoteSetCurrentSourceAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetCurrentSourceAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source _value);
        COMMONAPI_EXPORT virtual void onRemoteCurrentSourceAttributeChanged();

        COMMONAPI_EXPORT virtual bool onRemoteSetMetaDataAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetMetaDataAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData _value);
        COMMONAPI_EXPORT virtual void onRemoteMetaDataAttributeChanged();

        COMMONAPI_EXPORT virtual bool onRemoteSetPlayPositionAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetPlayPositionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition _value);
        COMMONAPI_EXPORT virtual void onRemotePlayPositionAttributeChanged();

        COMMONAPI_EXPORT virtual bool onRemoteSetPlayStatusAttribute(::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetPlayStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus _value);
        COMMONAPI_EXPORT virtual void onRemotePlayStatusAttributeChanged();


    private:
        AVInformationStubDefault *defaultStub_;
    };
private:
    AVInformationStubDefault::RemoteEventHandler remoteEventHandler_;

    ::v1::com::ivis::AVInformationProvider::AVInformationTypes::Source currentSourceAttributeValue_ {};
    ::v1::com::ivis::AVInformationProvider::AVInformationTypes::MetaData metaDataAttributeValue_ {};
    ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayPosition playPositionAttributeValue_ {};
    ::v1::com::ivis::AVInformationProvider::AVInformationTypes::PlayStatus playStatusAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace AVInformationProvider
} // namespace ivis
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_Information_STUB_DEFAULT
