/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.10.v201611111521.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_INFORMATION_INSTANCE_HPP_
#define V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_INFORMATION_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace com {
namespace ivis {
namespace AVInformationProvider {

const char * const AVInformation_com_ivis_AVInformationProvider_AVInformation_SomeIp = "com.ivis.AVInformationProvider.AVInformation.SomeIp";

const std::string AVInformation_INSTANCES[] = {
    AVInformation_com_ivis_AVInformationProvider_AVInformation_SomeIp
};

} // namespace AVInformationProvider
} // namespace ivis
} // namespace com
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_IVIS_AVINFORMATIONPROVIDER_AV_INFORMATION_INSTANCE_HPP_
