/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.10.v201610310807.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/com/ivis/AVInformationProvider/AVInformationSomeIPStubAdapter.hpp>
#include <v1/com/ivis/AVInformationProvider/AVInformation.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace ivis {
namespace AVInformationProvider {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createAVInformationSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< AVInformationSomeIPStubAdapter<::v1::com::ivis::AVInformationProvider::AVInformationStub>>(_address, _connection, _stub);
}

void initializeAVInformationSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:com.ivis.AVInformationProvider.AVInformation:v1_0:com.ivis.AVInformationProvider.AVInformation.SomeIp",
         0x7d0, 0x834, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        AVInformation::getInterface(),
        &createAVInformationSomeIPStubAdapter);
}

INITIALIZER(registerAVInformationSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeAVInformationSomeIPStubAdapter);
}
} // namespace AVInformationProvider
} // namespace ivis
} // namespace com
} // namespace v1
