/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.10.v201611111523.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_COM_IVIS_VEHICLEDATAMANAGER_VEHICLE_DATA_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_
#define V1_COM_IVIS_VEHICLEDATAMANAGER_VEHICLE_DATA_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace ivis {
namespace VehicleDataManager {
namespace VehicleDataManagerTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StringDeployment
> VehicleSpeedDeployment_t;

typedef CommonAPI::EmptyDeployment TransmissionGearStatusDeployment_t;


// typecollection-specific deployments

} // namespace VehicleDataManagerTypes_
} // namespace VehicleDataManager
} // namespace ivis
} // namespace com
} // namespace v1

#endif // V1_COM_IVIS_VEHICLEDATAMANAGER_VEHICLE_DATA_MANAGER_TYPES_DBUS_DEPLOYMENT_HPP_
