/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.10.v201611111521.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_IVIS_VEHICLEDATAMANAGER_Vehicle_Data_Manager_STUB_DEFAULT_HPP_
#define V1_COM_IVIS_VEHICLEDATAMANAGER_Vehicle_Data_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/ivis/VehicleDataManager/VehicleDataManagerStub.hpp>
#include <sstream>

#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif

namespace v1 {
namespace com {
namespace ivis {
namespace VehicleDataManager {

/**
 * Provides a default implementation for VehicleDataManagerStubRemoteEvent and
 * VehicleDataManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT VehicleDataManagerStubDefault
    : public virtual VehicleDataManagerStub {
public:
    COMMONAPI_EXPORT VehicleDataManagerStubDefault();

    COMMONAPI_EXPORT VehicleDataManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< VehicleDataManagerStubAdapter> &_adapter);

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);

    COMMONAPI_EXPORT virtual const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed& getVehicleSpeedAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed& getVehicleSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setVehicleSpeedAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed _value);
    COMMONAPI_EXPORT virtual void setVehicleSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed _value);
    COMMONAPI_EXPORT virtual const std::string& getVinAttribute();
    COMMONAPI_EXPORT virtual const std::string& getVinAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setVinAttribute(std::string _value);
    COMMONAPI_EXPORT virtual void setVinAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _value);
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus& getTransmissionGearStatusAttribute();
    COMMONAPI_EXPORT virtual const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus& getTransmissionGearStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setTransmissionGearStatusAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus _value);
    COMMONAPI_EXPORT virtual void setTransmissionGearStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus _value);
    COMMONAPI_EXPORT virtual const bool& getDrivingRestrictionAttribute();
    COMMONAPI_EXPORT virtual const bool& getDrivingRestrictionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setDrivingRestrictionAttribute(bool _value);
    COMMONAPI_EXPORT virtual void setDrivingRestrictionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);
    COMMONAPI_EXPORT virtual const bool& getLowFuelWarningAttribute();
    COMMONAPI_EXPORT virtual const bool& getLowFuelWarningAttribute(const std::shared_ptr<CommonAPI::ClientId> _client);
    COMMONAPI_EXPORT virtual void setLowFuelWarningAttribute(bool _value);
    COMMONAPI_EXPORT virtual void setLowFuelWarningAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);



    
protected:
    /**
     * description: This attribute contains the current speed of this vehicle. The unit of value is
     *   km/h or mph.
     */
    COMMONAPI_EXPORT virtual bool trySetVehicleSpeedAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed _value);
    COMMONAPI_EXPORT virtual bool validateVehicleSpeedAttributeRequestedValue(const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed &_value);
    COMMONAPI_EXPORT virtual void onRemoteVehicleSpeedAttributeChanged();
    /**
     * description: This attribute contains the VIN(Vehicle Identification Number as defined by ISO
     *   3779) information for this vehicle. It's 17 bytes long characters.
     */
    COMMONAPI_EXPORT virtual bool trySetVinAttribute(std::string _value);
    COMMONAPI_EXPORT virtual bool validateVinAttributeRequestedValue(const std::string &_value);
    COMMONAPI_EXPORT virtual void onRemoteVinAttributeChanged();
    /**
     * description: This attribute contains the current status of transmission gear.
     */
    COMMONAPI_EXPORT virtual bool trySetTransmissionGearStatusAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus _value);
    COMMONAPI_EXPORT virtual bool validateTransmissionGearStatusAttributeRequestedValue(const ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus &_value);
    COMMONAPI_EXPORT virtual void onRemoteTransmissionGearStatusAttributeChanged();
    COMMONAPI_EXPORT virtual bool trySetDrivingRestrictionAttribute(bool _value);
    COMMONAPI_EXPORT virtual bool validateDrivingRestrictionAttributeRequestedValue(const bool &_value);
    COMMONAPI_EXPORT virtual void onRemoteDrivingRestrictionAttributeChanged();
    COMMONAPI_EXPORT virtual bool trySetLowFuelWarningAttribute(bool _value);
    COMMONAPI_EXPORT virtual bool validateLowFuelWarningAttributeRequestedValue(const bool &_value);
    COMMONAPI_EXPORT virtual void onRemoteLowFuelWarningAttributeChanged();
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual VehicleDataManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(VehicleDataManagerStubDefault *_defaultStub);

        /**
         * description: This attribute contains the current speed of this vehicle. The unit of value is
         *   km/h or mph.
         */
        COMMONAPI_EXPORT virtual bool onRemoteSetVehicleSpeedAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetVehicleSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed _value);
        COMMONAPI_EXPORT virtual void onRemoteVehicleSpeedAttributeChanged();

        /**
         * description: This attribute contains the VIN(Vehicle Identification Number as defined by ISO
         *   3779) information for this vehicle. It's 17 bytes long characters.
         */
        COMMONAPI_EXPORT virtual bool onRemoteSetVinAttribute(std::string _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetVinAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _value);
        COMMONAPI_EXPORT virtual void onRemoteVinAttributeChanged();

        /**
         * description: This attribute contains the current status of transmission gear.
         */
        COMMONAPI_EXPORT virtual bool onRemoteSetTransmissionGearStatusAttribute(::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetTransmissionGearStatusAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus _value);
        COMMONAPI_EXPORT virtual void onRemoteTransmissionGearStatusAttributeChanged();

        COMMONAPI_EXPORT virtual bool onRemoteSetDrivingRestrictionAttribute(bool _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetDrivingRestrictionAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);
        COMMONAPI_EXPORT virtual void onRemoteDrivingRestrictionAttributeChanged();

        COMMONAPI_EXPORT virtual bool onRemoteSetLowFuelWarningAttribute(bool _value);
        COMMONAPI_EXPORT virtual bool onRemoteSetLowFuelWarningAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value);
        COMMONAPI_EXPORT virtual void onRemoteLowFuelWarningAttributeChanged();


    private:
        VehicleDataManagerStubDefault *defaultStub_;
    };
private:
    VehicleDataManagerStubDefault::RemoteEventHandler remoteEventHandler_;

    /**
     * description: This attribute contains the current speed of this vehicle. The unit of value is
     *   km/h or mph.
     */
    ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::VehicleSpeed vehicleSpeedAttributeValue_ {};
    /**
     * description: This attribute contains the VIN(Vehicle Identification Number as defined by ISO
     *   3779) information for this vehicle. It's 17 bytes long characters.
     */
    std::string vinAttributeValue_ {};
    /**
     * description: This attribute contains the current status of transmission gear.
     */
    ::v1::com::ivis::VehicleDataManager::VehicleDataManagerTypes::TransmissionGearStatus transmissionGearStatusAttributeValue_ {};
    bool drivingRestrictionAttributeValue_ {};
    bool lowFuelWarningAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace VehicleDataManager
} // namespace ivis
} // namespace com
} // namespace v1


// Compatibility
namespace v1_1 = v1;

#endif // V1_COM_IVIS_VEHICLEDATAMANAGER_Vehicle_Data_Manager_STUB_DEFAULT
